### PR TITLE
delete with star (*) prefix. createCommand can handle undefined

### PR DESCRIPTION
**Pull request by kim-lindhard-dfds**
Now we can delete Access Control Lists with star prefix.

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |1|
| **Quality Gates** |OK|
| **Description** |Low Risk: The change is low risk as it touches less code than 97% of your change sets.. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |5|
| **Quality Gates** |OK|
| **Description** |Medium Risk (5 where 10 is the highest): The change involves more modules and modified lines of code than 81% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |5|
| **Quality Gates** |OK|
| **Description** |Medium Risk (5 where 10 is the highest): The change involves more modules and modified lines of code than 81% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |6|
| **Quality Gates** |OK|
| **Description** |Medium Risk (6 where 10 is the highest): The change involves more modules and modified lines of code than 81% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 50% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Review by SEQUOIIA — APPROVED** [review]
Seems about right. 14 ACLs is created as expected.

**Pull request merged**
