### PR TITLE
Ch2042/config in topic creation

### PR DESCRIPTION
**Pull request by kim-lindhard-dfds**
Tika server and client updated to facilitate setting configurations in the create topic command.

* Added a endpoint for topic describe at /topics/{topicName}
* Created a integration test for setting configurations at topic create

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 442 lines, deletes 120 lines of code in 16 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping code health checks for those files.</li></ul>|

**Comment by SEQUOIIA** [comment]
I've raised a potential concern in the Clubhouse story.

---

Integration test 'SameTopicNameTwice' seems to be broken when running Tika in 'notconnected' mode.

When running integration tests in 'connected' mode, all hell breaks loose. 
Screenshot 2020-04-05 at 11 33 07 PM

Actually.. running integration tests in 'connected' mode on master fails the same way. Perhaps more breaking changes from the ccloud CLI ?

Going back to a couple of commits before we removed some logging from executeCli, tells a bit more..

image

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 623 lines, deletes 178 lines of code in 29 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>6 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping code health checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 653 lines, deletes 201 lines of code in 29 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>6 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping code health checks for those files.</li></ul>|

**Review by SEQUOIIA — APPROVED** [review]
Awesome stuff.

**Pull request merged**
