### PR TITLE
Add fix in to create valid command for creating a access control in confluent

### PR DESCRIPTION
**Pull request by jdsmithit**
look like a there was a breaking change in the confluent CLI this fix is to address this

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene PR Check
---
**View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/ad3a65581d314d990238c43773d5a4a31aa286b2)

|||
| --- | ---- |
| **Quality Gates** |FAILED|
| **Recommended Review Level** |Detailed -- Inspect the code that degrades in code health.|


## Warnings


___Degrades in Code Health___

* tika/server/src/server/wrapper/notConnected/NotConnectedAccessControlLists.ts degrades from a Code Health of 8.66 -&gt; 8.33

---


## Code Health Delta Descriptions

**server/src/server/wrapper/notConnected/NotConnectedAccessControlLists.ts**

___Degradations___

* Complex Method : NotConnectedAccessControlLists.createAccessControlListObject has a cyclomatic complexity of 9, threshold = 9 - new issue

---

**Review by SEQUOIIA — APPROVED** [review]
lol

**Comment by SEQUOIIA** [comment]
https://user-images.githubusercontent.com/1633308/179475364-c6ad2224-0afb-4700-845e-36fa9e7d71b7.mp4

**Comment by samidbb** [comment]
@jdsmithit should this be discarded?

**Comment by jdsmithit** [comment]
Gone @samidbb

**Pull request closed without merging**
