### PR TITLE
maintenance/update cli tooling

### PR DESCRIPTION
**Pull request by wcarlsen**
- Install confluent cli tool instead of the soon to be EOL ccloud cli
- Changed entrypoint login scripts and updated cli executable to confluent
- Updated CcloudCluster class and changed parsing to utilize json
- Alter list topics to utilize json output
- Alter describe topics to utilize json output
- Alter list service-accounts to utilize json output
- use list service-account
- Alter create service-accounts to utilize json output
- Alter api-keys to utilize json output
- Alter acls to utilize json output
- Convert ACL UserId from long to string, to make it clear that it is not in use
- Convert ACL serviceAccountId from long to string

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene Delta Analysis Results

 **View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/e6005739fefc68f3a570de98e9c668a4e6eaf288)


|||
| --- | ---- |
| **Recommended Review Level** |Detailed -- Increased risk for defects: The change involves more modules and modified lines of code than 99% of the historic high-risk change sets. The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|


## Review of New Files

0 new file(s) below the threshold for new code (9).
1 new file(s) where the code health is above the threshold.

**Comment by wcarlsen** [comment]
Closes https://github.com/dfds/cloudplatform/issues/748

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

# CodeScene Delta Analysis Results

 **View detailed results** in [CodeScene](https://codescene.dfds.cloud/32/delta-analysis/view/f125b0a66d1399af8fc5ed410da5741ce4c79170)


|||
| --- | ---- |
| **Recommended Review Level** |Detailed -- Increased risk for defects: The change involves more modules and modified lines of code than 99% of the historic high-risk change sets. The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|


## Review of New Files

0 new file(s) below the threshold for new code (9).
1 new file(s) where the code health is above the threshold.

**Review by jdsmithit — COMMENTED** [review]
it is a good chance to look at adding a read me file?

**Review by SEQUOIIA — APPROVED** [review]
Love me some Confluent CLI updates. Weee.

**Pull request merged**
